Phase2
Star-Academy/Summer1400-SE-Team19 pull request #2
Opened 2021-07-26 09:08 UTC by aradmaleki02

2021-07-26 10:05 UTC, MohammadMoshtagh approved these changes
kamet garm khodaii

2021-07-26 12:04 UTC, amirarab888 requested changes
در کل خوب بود ولی این کامنتا درست بشن

2021-07-26 12:04 UTC, amirarab888 commented on src/DataContainer.java
> +    private static final DataContainer INSTANCE = new DataContainer();
چرا استاتیکه؟

2021-07-26 12:04 UTC, amirarab888 commented on src/words/Word.java
> +    protected String word;
چرا کلاس ابسترکت؟ چرا اینترفیس نه؟

2021-07-26 12:04 UTC, amirarab888 commented on src/words/PositiveWordAction.java
> +        priority = 2;
چرا این جا داری یه متغیر رو مقدار میدی؟

2021-07-26 12:04 UTC, amirarab888 commented on src/words/NegativeWordAction.java
> +    public void action(ArrayList<Integer> wordSearchResult, ArrayList<Integer> userSearchResult) {
اسم تابع باید فعل باشه

2021-07-26 12:04 UTC, amirarab888 commented on src/Searcher.java
> +    private static final Searcher INSTANCE = new Searcher();
instance
اسم خوبی نیست

2021-07-26 12:04 UTC, amirarab888 commented on src/DataContainer.java
> +    public ArrayList<Integer> getAddress(String fileName) {
getAddress?
این چه اسمیه؟

2021-07-26 12:04 UTC, amirarab888 commented on src/DataContainer.java
> +    public void addAddress(String word, Integer address) {
این چه اسمیه؟

2021-07-26 12:04 UTC, amirarab888 commented on src/DataContainer.java
> +    private final HashMap<String, ArrayList<Integer>> allData = new HashMap<>();
چرا از استرینگ به
hashSet
نیست؟

2021-07-26 12:04 UTC, amirarab888 commented on src/DataInitializer.java
> +public class DataInitializer {
DataProvider
به نظرم اسم بهتریه

2021-07-26 12:04 UTC, amirarab888 commented on src/DataInitializer.java
> +        INSTANCE = new DataInitializer();
چرا تو
constructor
این اتفاق نیافتاده؟

2021-07-26 12:04 UTC, amirarab888 commented on src/DataInitializer.java
> +                e.printStackTrace();
خطای مناسب داده بشه

2021-07-26 12:04 UTC, amirarab888 commented on src/DataInitializer.java
> +            dataContainer.addAddress(word, fileName);
این سه خز میتونه یه تابع باشه

2021-07-26 12:04 UTC, amirarab888 commented on src/Searcher.java
> +    private static final Searcher INSTANCE = new Searcher();
این جا 
new
نشه

2021-07-26 12:04 UTC, amirarab888 commented on src/Searcher.java
> +        return INSTANCE;
اگه برنامت بعدا بخواد چندین کلاینت رو هندل کنه, با این روش ممکنه 
concurretnException
بخوری

2021-07-26 12:04 UTC, amirarab888 commented on src/Main.java
> +            Searcher.getINSTANCE().run();
خوندن از فایل ها ربطی به سرچ کردن نداره و باید توی دو تا اجرا کننده جدا باشن

2021-07-26 12:04 UTC, amirarab888 commented on src/Searcher.java
>      private String processInput(String input) {
کار این تابع خیلی مشکوکه

2021-07-26 12:04 UTC, amirarab888 commented on src/Searcher.java
> +        return typeChecker.getWords();
باید 
new
کردن وابسته با تایپ نباشه
و اون تابع وابستع باشه
و غیر از 
constructor
جایی چیزی نباید 
new
بشه

2021-07-26 12:08 UTC, aradmaleki02 commented on src/DataContainer.java
> +    private static final DataContainer INSTANCE = new DataContainer();
singleton zadim ye instance static dare hamoono hey pass midim

2021-07-26 12:15 UTC, aradmaleki02 commented on src/DataContainer.java
> +    private final HashMap<String, ArrayList<Integer>> allData = new HashMap<>();
ma darim roosh add, retain, remove seda mikonim va ba arraylist codesh tamiz tare chon tartib dare

2021-07-26 12:25 UTC, aradmaleki02 commented on src/Main.java
> +            Searcher.getINSTANCE().run();
MultiThread bayad bezanim yani?

2021-07-26 12:35 UTC, aradmaleki02 commented on src/words/NegativeWordAction.java
> +    public void action(ArrayList<Integer> wordSearchResult, ArrayList<Integer> userSearchResult) {
fixed, will be committed.

2021-07-26 12:37 UTC, aradmaleki02 commented on src/Searcher.java
>      private String processInput(String input) {
we removed it. will be committed.

2021-07-26 12:38 UTC, aradmaleki02 commented on src/Searcher.java
> +        return INSTANCE;
ba tavajoh be inke gharar nabod multiThread bashe class ha ro singleton zadim, dar soorate lozoom mishe in ghesmat ro hazf kard be rahati.

2021-07-26 12:39 UTC, aradmaleki02 commented on src/Searcher.java
> +    private static final Searcher INSTANCE = new Searcher();
class singleton koja new beshe? to web didam in shekli mizanan

2021-07-26 12:41 UTC, aradmaleki02 commented on src/Searcher.java
> +    private static final Searcher INSTANCE = new Searcher();
fixed, will be committed.

2021-07-26 12:41 UTC, aradmaleki02 commented on src/DataInitializer.java
> +            dataContainer.addAddress(word, fileName);
fixed, will be committed.

2021-07-26 12:41 UTC, aradmaleki02 commented on src/DataInitializer.java
> +                e.printStackTrace();
fixed, will be committed.

2021-07-26 12:42 UTC, aradmaleki02 commented on src/DataInitializer.java
> +        INSTANCE = new DataInitializer();
its static! can't be done in constructor

2021-07-26 12:42 UTC, aradmaleki02 commented on src/DataInitializer.java
> +public class DataInitializer {
fixed, will be committed.

2021-07-26 12:42 UTC, aradmaleki02 commented on src/DataContainer.java
> +    public void addAddress(String word, Integer address) {
fixed, will be committed.

2021-07-26 12:42 UTC, aradmaleki02 commented on src/DataContainer.java
> +    public ArrayList<Integer> getAddress(String fileName) {
fixed, will be committed.

2021-07-31 14:15 UTC, amirarab888 requested changes

2021-07-31 14:15 UTC, amirarab888 commented on resources/SampleEnglishData/59221
> +
چرا این فایل ایگنور نشده؟

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/Main.java
> +        new UserInterface(parameterHolder.getUserInterfaceParameters(), new Searcher(dataProvider.getDataContainer())).run();
new 
کردن باید ریخته میشد توی یه متغیر بعد رو اون صدا میزدید
run
رو

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/Main.java
> +        new UserInterface(parameterHolder.getUserInterfaceParameters(), new Searcher(dataProvider.getDataContainer())).run();
چرا 
searcher
مثل بقیه توی 
parameterHolder
نیست؟

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/UserInterface.java
> +        searcher.search(wordsInObject);
کلا بهتره که تابع, آرگومان های ورودش رو تغییر نده و یه مقداری برگردونه و اون مقدار استفاده بشه

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/database/DataProvider.java
> +
الان لاگ رو نخواستیم ازتون ولی برای شبیه سازی حداقل یه پرینت بذارید شاید بد نباشه

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/Merger.java
> +        result = new HashSet<>();
این توی تابع انجام بشه وفیلدش هم توی تابع باشه

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/Searcher.java
> +            String wordInString = word.getWordInString();
کلمه
in
اضافیه
توی نام گذاری

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/Searcher.java
> +    public void search(ArrayList<Word> words) {
کاش 
void
بر نمیگردوند و ریزالت رو بر میگردوند

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/Searcher.java
> +            word.setSearchResult(searchResult);
کاش 
set
نبود و یه چیزی بر میگردوند

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/Searcher.java
> +            word.setSearchResult(searchResult);
اگر تابع 
void
برگردونه تست کردنش سخت میشه

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/TypeChecker.java
> +            wordInObject = checkWordCondition(word);
اینا چرا یه خط نشدن؟

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/modifiers/TypeChecker.java
> +        return sortResult(wordsInObject);
تو این دو خط هم دوباره بحث همین مطرحه که آرگومان ورودی تابع نباید توسط تابع تغییر کنه

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/parameterholders/DataContainerParameters.java
> +
خطوط بیشتر از یکی فاصله پاک بشن

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/parameterholders/ParameterHolder.java
> +        return dataProviderParameters;
اینا قضیش چیه؟

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/parameterholders/ParameterHolder.java
> +        return mergerParameters;
اینا قضیش چیه؟

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/parameterholders/ParameterHolder.java
> +        return userInterfaceParameters;
اینا قضیش چیه؟

2021-07-31 14:15 UTC, amirarab888 commented on src/main/java/parameterholders/TypeCheckerParameters.java
> +        return wordsInObject;
اینا رو توضیح میخوام

2021-08-28 06:26 UTC, merged